---
apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: welcome-message
  namespace: esx-system
spec:
  layertype: Incremental
  profile: >
    {
      "esx": {
          "system": {
            "welcome_message": {
                "message": "{align:left}{color:white} \n\n\n\n\tVMware Edge Cloud Orchestrator - Edge Host Is The Bestest{/color}{/align}\n\n\n\n\n\n\n\n\n{align:left}{color:yellow}"
            }
          }
      }
    }
