apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: best-effort-ec-small
  # No resource requests/reservations.
  # Memory overcommit possible.
spec:
  # VM operator controller name for VirtualMachine class
  # is different so addition of controllerName attr with invalid
  # value makes vm operator ignore this VM CRD instance.
  # This is majorly done because vm operator doesn't have all the
  # needed capabilities to deploy ec worker vm.
  controllerName: vmoperator.vmware.com/ecworker
  hardware:
    cpus: 4
    memory: 8Gi
---
apiVersion: v1
kind: Namespace
metadata:
  name: ec-system
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: ec-worker
  namespace: ec-system
spec:
  className: best-effort-ec-small
  imageName: ec-wrkr.ova
  powerState: poweredOff
  vmMetadata:
    configMapName: user-data-ubuntu
    transport: CloudInit

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-data-ubuntu
  namespace: default
data:
  user-data: |
    #cloud-config
    runcmd:
      - sudo rm -f /etc/netplan/*.yaml
      - |
        cat <<EOF > /etc/netplan/50-cloud-init.yaml
        network:
            ethernets:
                eth0:
                    dhcp4: no
                    addresses:
                      - 172.16.227.186/16
                    routes:
                      - to: default
                        via: 172.16.255.254
                    nameservers:
                        addresses: [8.8.8.8]
            version: 2
        EOF
      - sudo netplan apply
